version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake