services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    restart: always
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379